-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["terreno1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3465, 17  ,  3462, 20  ,  3461, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   812, -72  ,  805, -73  ,  809, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   681, -72  ,  673, -72  ,  677, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   704, -72  ,  696, -72  ,  700, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   727, -72  ,  719, -72  ,  723, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   750, -72  ,  742, -72  ,  746, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   773, -72  ,  765, -72  ,  769, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   796, -72  ,  788, -72  ,  792, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   819, -72  ,  812, -72  ,  815, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   850, -72  ,  842, -72  ,  846, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   873, -72  ,  865, -72  ,  869, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   896, -72  ,  888, -72  ,  892, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   919, -72  ,  911, -72  ,  915, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   942, -72  ,  934, -72  ,  938, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   965, -72  ,  957, -72  ,  961, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   988, -72  ,  980, -72  ,  984, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1011, -72  ,  1003, -72  ,  1007, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1042, -72  ,  1034, -72  ,  1038, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1065, -72  ,  1057, -72  ,  1061, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1088, -72  ,  1080, -72  ,  1084, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2705, -119  ,  2696, -118  ,  2700, -120  ,  2704, -121  ,  2706, -121  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2736, -119  ,  2726, -118  ,  2731, -120  ,  2735, -121  ,  2737, -121  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   834, -73  ,  828, -73  ,  832, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1026, -73  ,  1020, -73  ,  1024, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2767, -118  ,  2757, -118  ,  2758, -119  ,  2761, -121  ,  2768, -121  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   690, -73  ,  681, -72  ,  685, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   713, -73  ,  704, -72  ,  708, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   736, -73  ,  727, -72  ,  731, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   759, -73  ,  750, -72  ,  754, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   782, -73  ,  773, -72  ,  777, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   805, -73  ,  796, -72  ,  800, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   828, -73  ,  819, -72  ,  823, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   859, -73  ,  850, -72  ,  854, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   882, -73  ,  873, -72  ,  877, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   905, -73  ,  896, -72  ,  900, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   928, -73  ,  919, -72  ,  923, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   951, -73  ,  942, -72  ,  946, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   974, -73  ,  965, -72  ,  969, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   997, -73  ,  988, -72  ,  992, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1020, -73  ,  1011, -72  ,  1015, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1051, -73  ,  1042, -72  ,  1046, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1074, -73  ,  1065, -72  ,  1069, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   673, -72  ,  667, -73  ,  670, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   842, -72  ,  836, -73  ,  838, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1034, -72  ,  1028, -73  ,  1030, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2703, -124  ,  2704, -121  ,  2700, -120  ,  2699, -126  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1098, -72  ,  1088, -72  ,  1092, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2731, -120  ,  2728, -120  ,  2728, -123  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2700, -120  ,  2696, -118  ,  2694, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2731, -120  ,  2726, -118  ,  2724, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3532, 17  ,  3528, 17  ,  3530, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3475, 18  ,  3476, 20  ,  3470, 17  ,  3472, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2700, -120  ,  2697, -120  ,  2698, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3470, 17  ,  3468, 17  ,  3469, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2761, -121  ,  2758, -119  ,  2760, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2673, -121  ,  2669, -122  ,  2669, -127  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2675, -118  ,  2673, -121  ,  2675, -122  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2735, -121  ,  2731, -120  ,  2731, -127  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2765, -121  ,  2761, -121  ,  2761, -127  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2796, -121  ,  2792, -122  ,  2792, -127  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2798, -118  ,  2796, -121  ,  2798, -122  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3528, 17  ,  3525, 18  ,  3527, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3468, 17  ,  3465, 17  ,  3466, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -778, -287  ,  -809, -271  ,  -808, -287  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -809, -271  ,  -839, -256  ,  -838, -271  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3538, 20  ,  3536, 18  ,  3538, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2669, -122  ,  2673, -121  ,  2675, -118  ,  2665, -118  ,  2663, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2758, -119  ,  2757, -118  ,  2755, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2792, -122  ,  2796, -121  ,  2798, -118  ,  2788, -118  ,  2786, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3317, -36  ,  3328, -34  ,  3328, -26  ,  3318, -33  ,  3316, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3088, -42  ,  3093, -33  ,  3064, -26  ,  3062, -31  ,  3065, -40  ,  3075, -47  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3181, -41  ,  3168, -62  ,  3180, -58  ,  3185, -49  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2129, -129  ,  2165, -125  ,  2171, -121  ,  2172, -118  ,  2109, -120  ,  2117, -129  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3155, -47  ,  3127, -40  ,  3124, -47  ,  3127, -56  ,  3136, -62  ,  3150, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3182, -28  ,  3155, -47  ,  3165, -61  ,  3168, -62  ,  3181, -41  ,  3185, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3311, -44  ,  3317, -51  ,  3325, -53  ,  3334, -46  ,  3336, -40  ,  3328, -34  ,  3317, -36  ,  3312, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3119, -42  ,  3124, -31  ,  3093, -33  ,  3097, -42  ,  3106, -47  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3498, 15  ,  3496, 16  ,  3497, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2638, -149  ,  -3149, -68  ,  -2991, -224  ,  -2713, -225  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3165, -61  ,  3155, -47  ,  3158, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3318, -33  ,  3328, -26  ,  3319, -26  ,  3317, -30  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3470, 17  ,  3476, 20  ,  3462, 20  ,  3465, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3494, 18  ,  3493, 20  ,  3493, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3503, 16  ,  3502, 16  ,  3503, 13  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3507, 20  ,  3506, 17  ,  3507, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3507, 20  ,  3493, 20  ,  3494, 18  ,  3502, 16  ,  3503, 16  ,  3506, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3525, 18  ,  3524, 20  ,  3524, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3528, 17  ,  3532, 17  ,  3536, 18  ,  3538, 20  ,  3524, 20  ,  3525, 18  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2063, -130  ,  2067, -128  ,  2048, -121  ,  2054, -128  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -839, -256  ,  -932, -225  ,  -902, -255  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   694, -78  ,  696, -72  ,  690, -73  ,  692, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   717, -78  ,  719, -72  ,  713, -73  ,  715, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   740, -78  ,  742, -72  ,  736, -73  ,  738, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   763, -78  ,  765, -72  ,  759, -73  ,  761, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   786, -78  ,  788, -72  ,  782, -73  ,  784, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   863, -78  ,  865, -72  ,  859, -73  ,  861, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   886, -78  ,  888, -72  ,  882, -73  ,  884, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   909, -78  ,  911, -72  ,  905, -73  ,  907, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   932, -78  ,  934, -72  ,  928, -73  ,  930, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   955, -78  ,  957, -72  ,  951, -73  ,  953, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   978, -78  ,  980, -72  ,  974, -73  ,  976, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1001, -78  ,  1003, -72  ,  997, -73  ,  999, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1055, -78  ,  1057, -72  ,  1051, -73  ,  1053, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1078, -78  ,  1080, -72  ,  1074, -73  ,  1076, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1758, -116  ,  1372, -56  ,  1435, -118  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1178, -118  ,  -1515, 67  ,  -1330, -118  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1997, -130  ,  2042, -125  ,  2048, -121  ,  1987, -118  ,  1991, -127  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3476, 20  ,  3475, 18  ,  3476, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3502, 16  ,  3494, 18  ,  3496, 16  ,  3498, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3155, -47  ,  3182, -28  ,  3124, -31  ,  3127, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   482, 5  ,  -1515, 67  ,  -409, -72  ,  329, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -409, -72  ,  -1515, 67  ,  -1178, -118  ,  -686, -287  ,  -624, -287  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2097, -134  ,  2109, -120  ,  2067, -128  ,  2075, -136  ,  2081, -138  ,  2089, -138  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3536, 18  ,  3532, 17  ,  3532, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1312, -56  ,  1128, -72  ,  1217, -117  ,  1250, -118  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3896, -17  ,  -4280, -56  ,  -4248, -88  ,  -4143, -102  ,  -4064, -102  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2027, -138  ,  2034, -135  ,  2042, -125  ,  2006, -129  ,  2012, -135  ,  2019, -138  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2157, -135  ,  2165, -125  ,  2129, -129  ,  2136, -136  ,  2142, -138  ,  2150, -138  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2048, -121  ,  2042, -125  ,  2044, -125  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2171, -121  ,  2165, -125  ,  2167, -125  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4079, -379  ,  4106, -57  ,  4107, 143  ,  4078, -179  ,  4076, -377  ,  4078, -379  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1022, -225  ,  -1178, -118  ,  -1055, -240  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -932, -225  ,  -1178, -118  ,  -1022, -225  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3328, -34  ,  3336, -40  ,  3334, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2910, -26  ,  2757, -118  ,  2798, -118  ,  2817, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   673, -72  ,  665, -72  ,  667, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2109, -120  ,  2048, -121  ,  2067, -128  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -687, -302  ,  -778, -287  ,  -777, -302  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2559, -71  ,  -3236, 20  ,  -3149, -68  ,  -2638, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3124, -31  ,  3064, -26  ,  3093, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3462, 20  ,  3319, -26  ,  3370, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4143, -102  ,  -4248, -88  ,  -4220, -102  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   696, -72  ,  482, 5  ,  681, -72  ,  690, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   719, -72  ,  482, 5  ,  704, -72  ,  713, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   742, -72  ,  482, 5  ,  727, -72  ,  736, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   765, -72  ,  482, 5  ,  750, -72  ,  759, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   788, -72  ,  482, 5  ,  773, -72  ,  782, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   812, -72  ,  482, 5  ,  796, -72  ,  805, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   865, -72  ,  482, 5  ,  850, -72  ,  859, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   888, -72  ,  482, 5  ,  873, -72  ,  882, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   911, -72  ,  482, 5  ,  896, -72  ,  905, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   934, -72  ,  482, 5  ,  919, -72  ,  928, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   957, -72  ,  482, 5  ,  942, -72  ,  951, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   980, -72  ,  482, 5  ,  965, -72  ,  974, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1003, -72  ,  482, 5  ,  988, -72  ,  997, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1057, -72  ,  1042, -72  ,  1051, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1080, -72  ,  1065, -72  ,  1074, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2706, -118  ,  2696, -118  ,  2705, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2407, 51  ,  -3236, 20  ,  -2559, -71  ,  -2499, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4526, -56  ,  -4557, 142  ,  -4555, -333  ,  -4526, -332  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2737, -118  ,  2726, -118  ,  2736, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -687, -302  ,  -686, -301  ,  -686, -287  ,  -809, -271  ,  -778, -287  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4105.7822265625, -231.34783935546875  ,  4079, -379  ,  4107, -379  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4106, -57  ,  4079, -379  ,  4105.7822265625, -231.34783935546875  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   681, -72  ,  482, 5  ,  635, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -686, -287  ,  -839, -256  ,  -809, -271  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3182, -28  ,  3183, -26  ,  3064, -26  ,  3124, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3820, 20  ,  -4354, -55  ,  -4280, -56  ,  -3896, -17  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1341, -41  ,  1057, -72  ,  1128, -72  ,  1312, -56  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -686, -287  ,  -1178, -118  ,  -932, -225  ,  -839, -256  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   836, -73  ,  842, -72  ,  482, 5  ,  819, -72  ,  828, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1028, -73  ,  1034, -72  ,  1011, -72  ,  1020, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1687, 139  ,  -1416, 145  ,  -1557, 148  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1903.60888671875, -116.13043212890625  ,  1341, -41  ,  1372, -56  ,  1758, -116  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1902, 142  ,  -1987, 136  ,  -1687, 139  ,  -1781, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2172, -118  ,  1341, -41  ,  1987, -118  ,  2048, -121  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -557, 145  ,  -263, 145  ,  -416, 150  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3563, 145  ,  -4526, -56  ,  -3331, 145  ,  -3452, 148  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1090, 139  ,  -837, 139  ,  -960, 142  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -837, 139  ,  487.05126953125, 142.99371337890625  ,  -696, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3820, 20  ,  -4449, -55  ,  -4354, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   346.0498046875, 143.99371337890625  ,  487.05126953125, 142.99371337890625  ,  421.05029296875, 144.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2357, 130  ,  -1987, 136  ,  -2084, 139  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   705.05322265625, 142.99371337890625  ,  806.05419921875, 142.99371337890625  ,  755.0537109375, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3462, 20  ,  3183, -26  ,  3319, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4555, -333  ,  -4557, -229  ,  -4557, -332  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3187, 142  ,  -4526, -56  ,  -4524, -56  ,  -2972, 136  ,  -3105, 142  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2972, 136  ,  -3820, 20  ,  -2373, 67  ,  -2481, 130  ,  -2796, 139  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2373, 67  ,  -3820, 20  ,  -2407, 51  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3958.0859375, 140.99365234375  ,  3493, 20  ,  4106, 143  ,  4025.0869140625, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3462, 20  ,  3064, -26  ,  3183, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1376.06005859375, 142.99371337890625  ,  1544.0615234375, 141.99371337890625  ,  1456.06103515625, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3462, 20  ,  -2357, 130  ,  -1515, 67  ,  3064, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4107, 143  ,  4076, 20  ,  4078, -179  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4107, 143  ,  3966.65234375, 20.82611083984375  ,  4076, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4107, 143  ,  3655.7822265625, 20.82611083984375  ,  3966.65234375, 20.82611083984375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4107, 143  ,  4106, 143  ,  3493, 20  ,  3655.7822265625, 20.82611083984375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1687, 139  ,  -1269, 142  ,  -1416, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3484.0810546875, 141.99371337890625  ,  3618.08203125, 141.99371337890625  ,  3551.08203125, 142.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1987, -118  ,  1341, -41  ,  1903.60888671875, -116.13043212890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1178.05810546875, 143.99371337890625  ,  1376.06005859375, 142.99371337890625  ,  1292.05908203125, 144.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1632, 142  ,  1783.06396484375, 141.99371337890625  ,  1710, 143  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3094.0771484375, 141.99371337890625  ,  3241.07861328125, 141.99371337890625  ,  3161.078125, 142.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4193, 142  ,  -4526, -56  ,  -3563, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   704, -72  ,  482, 5  ,  696, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4557, 142  ,  -4526, -56  ,  -4193, 142  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2567, -116  ,  1341, -41  ,  2172, -118  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3820, 20  ,  -4524, -56  ,  -4449, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -107, 145  ,  80.046875, 144.99371337890625  ,  -12.95361328125, 145.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4557, 142  ,  -4460, 145  ,  -4556, 143  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4526, -56  ,  -3187, 142  ,  -3331, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   727, -72  ,  482, 5  ,  719, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   750, -72  ,  482, 5  ,  742, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2867.0751953125, 142.99371337890625  ,  3094.0771484375, 141.99371337890625  ,  2990.076171875, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1783.06396484375, 141.99371337890625  ,  1924.0654296875, 140.99365234375  ,  1854, 142  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1687, 139  ,  -2357, 130  ,  -1090, 139  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3712.0830078125, 140.99365234375  ,  3493, 20  ,  3958.0859375, 140.99365234375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   773, -72  ,  482, 5  ,  765, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2723.07373046875, 143.99371337890625  ,  2378.0703125, 141.99371337890625  ,  2867.0751953125, 142.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   487.05126953125, 142.99371337890625  ,  -2357, 130  ,  3493, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   939.0556640625, 142.99371337890625  ,  869.05517578125, 141.99371337890625  ,  1544.0615234375, 141.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   705.05322265625, 142.99371337890625  ,  640.052734375, 141.99371337890625  ,  3493, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   796, -72  ,  482, 5  ,  788, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2129.0673828125, 142.99371337890625  ,  2027.06640625, 141.99371337890625  ,  2300.0693359375, 141.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2378.0703125, 141.99371337890625  ,  2548.07177734375, 142.99371337890625  ,  2466.07080078125, 142.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2548.07177734375, 142.99371337890625  ,  2723.07373046875, 143.99371337890625  ,  2642.07275390625, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   819, -72  ,  482, 5  ,  812, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   153.0478515625, 144.99371337890625  ,  80.046875, 144.99371337890625  ,  346.0498046875, 143.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   850, -72  ,  482, 5  ,  842, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3484.0810546875, 141.99371337890625  ,  2378.0703125, 141.99371337890625  ,  3712.0830078125, 140.99365234375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   873, -72  ,  482, 5  ,  865, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2910, -26  ,  2665, -118  ,  2757, -118  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   896, -72  ,  482, 5  ,  888, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1632, 142  ,  1544.0615234375, 141.99371337890625  ,  1924.0654296875, 140.99365234375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   919, -72  ,  482, 5  ,  911, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1341, -41  ,  482, 5  ,  1003, -72  ,  1057, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2665, -118  ,  2910, -26  ,  1341, -41  ,  2567, -116  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   942, -72  ,  482, 5  ,  934, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1924.0654296875, 140.99365234375  ,  3493, 20  ,  3712.0830078125, 140.99365234375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   965, -72  ,  482, 5  ,  957, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   988, -72  ,  482, 5  ,  980, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2378.0703125, 141.99371337890625  ,  3094.0771484375, 141.99371337890625  ,  2867.0751953125, 142.99371337890625  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   2910, -26  ,  482, 5  ,  1341, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2357, 130  ,  -837, 139  ,  -1090, 139  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   869.05517578125, 141.99371337890625  ,  3493, 20  ,  1924.0654296875, 140.99365234375  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2373, 67  ,  -1515, 67  ,  -2357, 130  ,  -2481, 130  }
                    }
                     ,
                    {
                    pe_fixture_id = "terreno1", density = 2, friction = 15, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3476, 20  ,  -2357, 130  ,  3462, 20  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

