-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["aereo"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -172.5, -16  ,  -171, 4.5  ,  -178.5, 5  ,  -178.5, -9  ,  -176.5, -19  ,  -173.5, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   146.5, 30  ,  141, 30.5  ,  137, 24.5  ,  146, 20.5  ,  149.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -185.5, 8  ,  -178.5, 5  ,  -171, 4.5  ,  -179, 13.5  ,  -185.5, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   128, 19.5  ,  142.5, 20  ,  146, 20.5  ,  137, 24.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   168.5, 9  ,  151, 15.5  ,  144.5, 16  ,  73, -61.5  ,  178.5, -25  ,  180.5, -23  ,  180.5, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -171, 14.5  ,  -171, 4.5  ,  -142, -12.5  ,  -138, 35.5  ,  -162, 33.5  ,  -169.5, 29  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -178.5, 53  ,  -177.5, 16  ,  -171, 4.5  ,  -172.5, 64  ,  -176.5, 65  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   158.5, -67  ,  165.5, -60  ,  171.5, -50  ,  175.5, -40  ,  178.5, -25  ,  146, -66.5  ,  151, -69.5  ,  155, -69.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44, 53.5  ,  -51.5, 51  ,  -58, 43.5  ,  -30, 43.5  ,  -35, 50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -166, -10.5  ,  -142, -12.5  ,  -171, 4.5  ,  -170.5, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -171, 4.5  ,  -177.5, 16  ,  -179, 13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   26, 47.5  ,  21, 40.5  ,  25, 38.5  ,  28, 47.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -142, -12.5  ,  -140.5, -45  ,  -100, 41.5  ,  -110, 41.5  ,  -138, 35.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -100, 41.5  ,  -140.5, -45  ,  -58, 43.5  ,  -73, 46.5  ,  -85, 46.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   151, -69.5  ,  146, -66.5  ,  150, -69.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -140.5, -45  ,  55, -61.5  ,  73, -61.5  ,  21, 40.5  ,  -6, 43.5  ,  -58, 43.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   178.5, -25  ,  73, -61.5  ,  139, -67.5  ,  146, -66.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -108, -48.5  ,  -140.5, -45  ,  -139, -47.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 38.5  ,  82, 29.5  ,  61, 34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   142.5, 20  ,  128, 19.5  ,  73, -61.5  ,  144.5, 16  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   82, 29.5  ,  128, 19.5  ,  83, 30.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   25, 38.5  ,  73, -61.5  ,  128, 19.5  ,  82, 29.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "aereo", density = 1, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   73, -61.5  ,  25, 38.5  ,  21, 40.5  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

