-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["n2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -169, -321  ,  665, -193  ,  674, -187  ,  -172, -319  ,  -171, -321  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   677, -185  ,  -727, -76  ,  -539, -153  ,  676, -187  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   524, -293  ,  520, -296  ,  522, -296  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   549, -274  ,  545, -277  ,  547, -277  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   562, -264  ,  558, -267  ,  560, -267  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -116, -357  ,  -60, -367  ,  -121, -354  ,  -120, -356  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   716, -159  ,  711, -162  ,  715, -161  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1000, -41  ,  -937, -41  ,  1000, 500  ,  -1000, 500  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   378, -408  ,  373, -412  ,  375, -412  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -147, -336  ,  22, -376  ,  -154, -331  ,  -152, -334  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   509, -304  ,  -169, -321  ,  502, -309  ,  507, -307  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -657, -116  ,  -665, -111  ,  -661, -115  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   724, -154  ,  716, -159  ,  720, -158  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   763, -131  ,  1000, 500  ,  -937, -41  ,  -848, -55  ,  753, -137  ,  759, -135  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -492, -196  ,  -498, -191  ,  -494, -196  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -333, -270  ,  -339, -265  ,  -335, -270  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   406, -386  ,  400, -391  ,  402, -391  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   412, -381  ,  406, -386  ,  408, -386  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   418, -376  ,  -169, -321  ,  412, -381  ,  414, -381  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   424, -371  ,  -169, -321  ,  418, -376  ,  420, -376  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   430, -366  ,  -169, -321  ,  424, -371  ,  426, -371  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   436, -361  ,  -169, -321  ,  430, -366  ,  432, -366  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   442, -356  ,  -169, -321  ,  436, -361  ,  438, -361  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   448, -351  ,  -169, -321  ,  442, -356  ,  444, -356  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   454, -346  ,  -169, -321  ,  448, -351  ,  450, -351  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   460, -341  ,  -169, -321  ,  454, -346  ,  456, -346  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -627, -134  ,  -539, -153  ,  -634, -130  ,  -633, -132  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   387, -401  ,  378, -408  ,  384, -405  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   753, -137  ,  -848, -55  ,  -736, -73  ,  746, -141  ,  752, -139  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -426, -208  ,  -492, -196  ,  -478, -208  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   543, -280  ,  545, -277  ,  537, -283  ,  539, -283  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31, -381  ,  351, -429  ,  22, -376  ,  27, -380  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -382, -227  ,  -221, -298  ,  -203, -302  ,  -393, -218  ,  -389, -223  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   502, -309  ,  -169, -321  ,  491, -317  ,  496, -315  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -676, -104  ,  -539, -153  ,  -684, -99  ,  -683, -101  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -108, -362  ,  -60, -367  ,  -116, -357  ,  -115, -359  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -498, -191  ,  -506, -184  ,  -500, -191  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -665, -111  ,  -676, -104  ,  -669, -110  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   131, -435  ,  351, -429  ,  121, -431  ,  123, -433  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   141, -439  ,  351, -429  ,  131, -435  ,  133, -437  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  927, -41  ,  1000, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   794, -112  ,  1000, 500  ,  781, -120  ,  790, -116  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   400, -391  ,  387, -401  ,  393, -398  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -373, -235  ,  -382, -227  ,  -375, -235  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   826, -94  ,  832, -89  ,  1000, 500  ,  817, -98  ,  821, -97  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -339, -265  ,  -354, -252  ,  -348, -259  ,  -341, -265  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   373, -412  ,  352, -427  ,  363, -421  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   236, -457  ,  272, -452  ,  314, -442  ,  351, -429  ,  159, -446  ,  170, -451  ,  204, -458  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -172, -319  ,  674, -187  ,  -185, -311  ,  -176, -318  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   159, -446  ,  351, -429  ,  141, -439  ,  153, -445  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -389  ,  31, -381  ,  32, -383  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   781, -120  ,  1000, 500  ,  763, -131  ,  777, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   607, -232  ,  -169, -321  ,  591, -243  ,  605, -235  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   693, -174  ,  -736, -73  ,  -727, -76  ,  677, -185  ,  691, -177  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -539, -153  ,  -627, -134  ,  -613, -143  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   591, -243  ,  -169, -321  ,  578, -252  ,  590, -245  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -684, -99  ,  -539, -153  ,  -699, -90  ,  -698, -92  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -133, -346  ,  -147, -336  ,  -135, -346  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   475, -329  ,  -169, -321  ,  462, -341  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -313, -285  ,  -221, -298  ,  -333, -270  ,  -318, -283  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   746, -141  ,  -736, -73  ,  724, -154  ,  740, -146  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -154, -331  ,  22, -376  ,  351, -429  ,  352, -427  ,  -169, -321  ,  -168, -323  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   817, -98  ,  1000, 500  ,  794, -112  ,  803, -108  ,  816, -100  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   894, -56  ,  1000, 500  ,  875, -66  ,  893, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   491, -317  ,  -169, -321  ,  477, -329  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   578, -252  ,  562, -264  ,  564, -264  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -634, -130  ,  -539, -153  ,  -657, -116  ,  -653, -120  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   121, -431  ,  351, -429  ,  48, -392  ,  52, -396  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   665, -193  ,  618, -225  ,  647, -207  ,  663, -196  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -354, -252  ,  -373, -235  ,  -356, -252  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   711, -162  ,  -736, -73  ,  693, -174  ,  695, -174  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  894, -56  ,  927, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -404, -212  ,  674, -187  ,  -539, -153  ,  -506, -184  ,  -492, -196  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   121, -431  ,  71, -406  ,  72, -408  ,  113, -429  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60, -367  ,  22, -376  ,  -147, -336  ,  -121, -354  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -506, -184  ,  -539, -153  ,  -508, -184  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -221, -298  ,  -313, -285  ,  -311, -288  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -736, -73  ,  -848, -55  ,  -785, -67  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -221, -298  ,  -373, -235  ,  -333, -270  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   875, -66  ,  1000, 500  ,  832, -89  ,  874, -68  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -221, -298  ,  -382, -227  ,  -373, -235  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -539, -153  ,  -676, -104  ,  -657, -116  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   48, -392  ,  351, -429  ,  31, -381  ,  43, -389  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -539, -153  ,  -727, -76  ,  -699, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   412, -381  ,  -169, -321  ,  352, -427  ,  400, -391  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   378, -408  ,  352, -427  ,  373, -412  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   387, -401  ,  352, -427  ,  378, -408  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   724, -154  ,  -736, -73  ,  711, -162  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   665, -193  ,  -169, -321  ,  607, -232  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   558, -267  ,  -169, -321  ,  537, -283  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -203, -302  ,  674, -187  ,  -404, -212  ,  -393, -218  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   537, -283  ,  -169, -321  ,  509, -304  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   578, -252  ,  -169, -321  ,  558, -267  }
                    }
                     ,
                    {
                    pe_fixture_id = "n2", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   674, -187  ,  -203, -302  ,  -185, -311  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

