-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["s5"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   663, 24  ,  659, 27  ,  660, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   216, -233  ,  209, -230  ,  212, -237  ,  216, -236  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   369, 53  ,  385, 56  ,  -259, 43  ,  -258, 41  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   209, -230  ,  197, -242  ,  205, -244  ,  212, -237  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   678, 19  ,  663, 24  ,  670, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   694, 12  ,  678, 19  ,  679, 13  ,  685, 8  ,  691, 8  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   705, 8  ,  711, 13  ,  711, 16  ,  696, 12  ,  699, 8  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   111, -257  ,  221, -127  ,  220, -117  ,  106, -255  ,  108, -257  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   190, -253  ,  196, -248  ,  197, -242  ,  180, -249  ,  184, -253  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   339, 38  ,  369, 53  ,  -234, 26  ,  -232, 23  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   316, 22  ,  320, 25  ,  -230, 23  ,  -228, 20  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   64, -232  ,  233, -82  ,  246, -56  ,  60, -229  ,  62, -232  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   320, 25  ,  316, 22  ,  318, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -264, 46  ,  385, 56  ,  -269, 49  ,  -268, 47  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -259, 43  ,  385, 56  ,  -264, 46  ,  -263, 44  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   219, -217  ,  216, -222  ,  218, -221  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   249, -51  ,  -198, -2  ,  -186, -12  ,  246, -56  ,  248, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   216, -222  ,  209, -230  ,  215, -226  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1000, -35  ,  -846, -23  ,  1000, 500  ,  -1000, 500  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   316, 22  ,  -218, 14  ,  -215, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   316, 22  ,  -213, 10  ,  -210, 6  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -203, 2  ,  316, 22  ,  -208, 6  ,  -205, 2  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   307, 15  ,  316, 22  ,  -203, 2  ,  -200, -2  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -31, -159  ,  246, -56  ,  -36, -155  ,  -33, -159  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   36, -212  ,  31, -208  ,  34, -212  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -234, 26  ,  369, 53  ,  -241, 31  ,  -239, 28  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -217  ,  36, -212  ,  38, -215  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   106, -255  ,  220, -117  ,  99, -252  ,  103, -255  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   931, -47  ,  901, -44  ,  907, -51  ,  916, -55  ,  920, -55  ,  927, -52  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   770, 5  ,  1000, 500  ,  761, 7  ,  765, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   949, -43  ,  954, -36  ,  1000, 500  ,  900, -40  ,  901, -44  ,  931, -47  ,  942, -47  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, -167  ,  246, -56  ,  -31, -159  ,  -27, -164  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -60, -135  ,  246, -56  ,  -66, -130  ,  -62, -135  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -36, -155  ,  246, -56  ,  -42, -150  ,  -38, -155  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   209, -230  ,  229, -173  ,  229, -162  ,  226, -141  ,  221, -127  ,  111, -257  ,  180, -249  ,  197, -242  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   129, -263  ,  150, -262  ,  168, -256  ,  180, -249  ,  111, -257  ,  120, -262  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   99, -252  ,  220, -117  ,  91, -248  ,  92, -250  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -218, 14  ,  316, 22  ,  -226, 20  ,  -224, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   17, -197  ,  246, -56  ,  9, -191  ,  11, -194  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -90, -109  ,  -97, -103  ,  -92, -109  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -83, -115  ,  -90, -109  ,  -85, -115  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   900, -40  ,  1000, 500  ,  880, -23  ,  891, -36  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -99, -103  ,  -97, -103  ,  -107, -92  ,  -106, -96  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   330, 32  ,  -230, 23  ,  320, 25  ,  328, 29  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -66, -130  ,  246, -56  ,  -74, -123  ,  -68, -130  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   307, 15  ,  299, 8  ,  301, 8  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -835, -20  ,  -846, -23  ,  -838, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -824, -17  ,  -835, -20  ,  -827, -19  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -813, -14  ,  -824, -17  ,  -816, -16  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   263, -31  ,  -198, -2  ,  257, -39  ,  263, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -74, -123  ,  -83, -115  ,  -76, -123  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   316, 22  ,  307, 15  ,  309, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   339, 38  ,  330, 32  ,  332, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, -178  ,  246, -56  ,  -21, -167  ,  -13, -175  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31, -208  ,  246, -56  ,  17, -197  ,  25, -205  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, -229  ,  246, -56  ,  43, -217  ,  49, -223  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   229, -173  ,  209, -230  ,  225, -209  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -118, -77  ,  246, -56  ,  -127, -67  ,  -127, -69  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   271, -21  ,  -198, -2  ,  263, -31  ,  271, -23  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -798, -10  ,  -813, -14  ,  -801, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   858, -17  ,  1000, 500  ,  843, -13  ,  846, -15  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   91, -248  ,  220, -117  ,  224, -104  ,  64, -232  ,  74, -240  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -186, -12  ,  -198, -2  ,  -188, -12  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -722, 9  ,  -739, 5  ,  -734, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   787, 1  ,  1000, 500  ,  770, 5  ,  782, 1  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42, -150  ,  246, -56  ,  -60, -135  ,  -49, -146  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   257, -39  ,  -198, -2  ,  249, -51  ,  251, -50  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  954, -36  ,  1000, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   678, 19  ,  711, 16  ,  717, 16  ,  1000, 500  ,  659, 27  ,  663, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   880, -23  ,  1000, 500  ,  858, -17  ,  872, -22  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   761, 7  ,  1000, 500  ,  742, 11  ,  746, 9  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -779, -5  ,  -798, -10  ,  -782, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -856, -27  ,  -846, -23  ,  -1000, -35  ,  -910, -36  ,  -885, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -107, -92  ,  -97, -103  ,  -83, -115  ,  -118, -77  ,  -118, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -241, 31  ,  369, 53  ,  -256, 41  ,  -255, 39  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   9, -191  ,  246, -56  ,  -7, -178  ,  7, -191  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   219, -217  ,  209, -230  ,  216, -222  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -699, 14  ,  -722, 9  ,  -703, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   233, -82  ,  64, -232  ,  224, -104  ,  233, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -162, -33  ,  -186, -12  ,  -164, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   696, 12  ,  711, 16  ,  678, 19  ,  694, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -348, 54  ,  1000, 500  ,  -410, 52  ,  -373, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43, -217  ,  246, -56  ,  31, -208  ,  36, -212  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -74, -123  ,  246, -56  ,  -118, -77  ,  -83, -115  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   246, -56  ,  -162, -33  ,  -127, -67  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   246, -56  ,  -186, -12  ,  -162, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   299, 8  ,  -198, -2  ,  271, -21  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   307, 15  ,  -198, -2  ,  299, 8  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   339, 38  ,  -230, 23  ,  330, 32  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   385, 56  ,  1000, 500  ,  -282, 53  ,  -269, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  787, 1  ,  843, -13  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  717, 16  ,  742, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  595, 37  ,  659, 27  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  488, 50  ,  595, 37  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  441, 54  ,  488, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  385, 56  ,  441, 54  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -348, 54  ,  -282, 53  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -522, 42  ,  -410, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -603, 31  ,  -522, 42  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -699, 14  ,  -603, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -722, 9  ,  -699, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -739, 5  ,  -722, 9  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -779, -5  ,  -739, 5  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -798, -10  ,  -779, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "s5", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -813, -14  ,  -798, -10  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

