-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["t11"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -770, -59  ,  -773, -57  ,  -772, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -767, -61  ,  -770, -59  ,  -769, -61  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -764, -63  ,  -767, -61  ,  -766, -63  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   488, -273  ,  485, -275  ,  487, -275  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -522, -206  ,  -526, -204  ,  -525, -206  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  -813, -37  ,  -811, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   12, -166  ,  688, -38  ,  698, -31  ,  7, -164  ,  9, -166  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56, -192  ,  666, -61  ,  683, -42  ,  52, -189  ,  54, -192  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   511, -257  ,  133, -258  ,  135, -261  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   511, -257  ,  137, -261  ,  139, -264  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   504, -262  ,  511, -257  ,  141, -264  ,  143, -267  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   515, -254  ,  69, -202  ,  511, -257  ,  513, -257  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   600, -169  ,  56, -192  ,  64, -198  ,  597, -173  ,  600, -171  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  718, -30  ,  1000, 500  ,  -1000, 500  ,  -1000, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40, -181  ,  683, -42  ,  35, -178  ,  36, -180  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   472, -283  ,  145, -267  ,  201, -295  ,  467, -286  ,  471, -285  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   485, -275  ,  480, -278  ,  484, -277  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -727, -90  ,  -732, -86  ,  -729, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -716, -99  ,  -721, -95  ,  -718, -99  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   69, -202  ,  597, -173  ,  64, -198  ,  67, -202  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   688, -38  ,  683, -42  ,  685, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   511, -257  ,  504, -262  ,  509, -260  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -631, -165  ,  -638, -162  ,  -634, -165  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   480, -278  ,  145, -267  ,  472, -283  ,  476, -282  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  879, -31  ,  1000, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -721, -95  ,  -727, -90  ,  -723, -95  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -710, -104  ,  -716, -99  ,  -712, -104  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -362, -157  ,  -710, -104  ,  -368, -162  ,  -366, -162  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -356, -152  ,  -710, -104  ,  -362, -157  ,  -360, -157  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   35, -178  ,  683, -42  ,  28, -174  ,  29, -176  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   524, -247  ,  515, -254  ,  521, -251  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   201, -295  ,  193, -292  ,  195, -294  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   64, -198  ,  56, -192  ,  58, -195  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -368, -162  ,  -375, -168  ,  -373, -168  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -526, -204  ,  -537, -197  ,  -530, -203  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -638, -162  ,  -652, -155  ,  -650, -158  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   113, -242  ,  104, -234  ,  111, -242  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   133, -258  ,  124, -251  ,  131, -258  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -303, -153  ,  -28, -155  ,  698, -31  ,  -340, -145  ,  -324, -151  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   161, -277  ,  145, -267  ,  155, -275  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -493, -215  ,  -449, -214  ,  -420, -206  ,  -404, -195  ,  -375, -168  ,  -522, -206  ,  -509, -212  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   193, -292  ,  145, -267  ,  190, -292  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   666, -61  ,  56, -192  ,  655, -78  ,  661, -71  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -346, -145  ,  -716, -99  ,  -710, -104  ,  -356, -152  ,  -354, -152  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  688, -38  ,  690, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -652, -155  ,  -638, -162  ,  -631, -165  ,  -592, -170  ,  -668, -144  ,  -663, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   104, -234  ,  93, -224  ,  102, -234  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   879, -31  ,  859, -33  ,  879, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   124, -251  ,  113, -242  ,  122, -251  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -792, -46  ,  -346, -145  ,  -340, -145  ,  698, -31  ,  -808, -39  ,  -804, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -552, -185  ,  -368, -162  ,  -564, -177  ,  -563, -179  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, -189  ,  683, -42  ,  40, -181  ,  41, -183  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   467, -286  ,  225, -303  ,  255, -312  ,  288, -318  ,  335, -322  ,  383, -321  ,  410, -314  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   736, -31  ,  1000, 500  ,  718, -30  ,  732, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -732, -86  ,  -346, -145  ,  -749, -73  ,  -738, -83  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   580, -193  ,  568, -206  ,  580, -195  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -404, -195  ,  -420, -206  ,  -406, -198  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   504, -262  ,  488, -273  ,  502, -265  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   623, -136  ,  612, -153  ,  622, -140  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -537, -197  ,  -552, -185  ,  -539, -197  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -592, -170  ,  -631, -165  ,  -627, -168  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -749, -73  ,  -346, -145  ,  -764, -63  ,  -763, -65  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   178, -287  ,  181, -287  ,  161, -277  ,  162, -279  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   640, -107  ,  623, -136  ,  629, -129  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   612, -153  ,  600, -169  ,  612, -155  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -773, -57  ,  -346, -145  ,  -792, -46  ,  -791, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   221, -303  ,  225, -303  ,  467, -286  ,  201, -295  ,  203, -297  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   597, -173  ,  69, -202  ,  515, -254  ,  524, -247  ,  580, -193  ,  597, -175  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   255, -312  ,  225, -303  ,  231, -306  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -526, -204  ,  -522, -206  ,  -375, -168  ,  -368, -162  ,  -552, -185  ,  -537, -197  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   181, -287  ,  145, -267  ,  161, -277  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   93, -224  ,  69, -202  ,  91, -224  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   655, -78  ,  640, -107  ,  642, -106  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -375, -168  ,  -404, -195  ,  -402, -195  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   467, -286  ,  431, -304  ,  434, -304  ,  466, -288  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  736, -31  ,  859, -33  ,  879, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   623, -136  ,  640, -107  ,  655, -78  ,  56, -192  ,  600, -169  ,  612, -153  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   568, -206  ,  524, -247  ,  526, -247  ,  568, -208  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -668, -144  ,  -710, -104  ,  -670, -144  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -592, -170  ,  -564, -177  ,  -368, -162  ,  -710, -104  ,  -668, -144  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   133, -258  ,  511, -257  ,  69, -202  ,  113, -242  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   504, -262  ,  145, -267  ,  480, -278  ,  485, -275  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   580, -193  ,  524, -247  ,  568, -206  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   201, -295  ,  145, -267  ,  193, -292  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -716, -99  ,  -346, -145  ,  -727, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -346, -145  ,  -732, -86  ,  -727, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   683, -42  ,  688, -38  ,  12, -166  ,  28, -174  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  -13, -157  ,  7, -164  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  -28, -155  ,  -13, -157  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -346, -145  ,  -773, -57  ,  -764, -63  }
                    }
                     ,
                    {
                    pe_fixture_id = "t11", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   698, -31  ,  -828, -35  ,  -813, -37  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

