-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["t12"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   316, -103  ,  91, -57  ,  96, -61  ,  313, -105  ,  315, -105  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   580, -130  ,  577, -128  ,  578, -130  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -696, -60  ,  -807, -73  ,  -702, -64  ,  -698, -63  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -426, -91  ,  -504, -87  ,  -495, -94  ,  -428, -94  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   398, -48  ,  425, -41  ,  87, -54  ,  89, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   130, -89  ,  126, -86  ,  128, -89  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   158, -110  ,  154, -107  ,  156, -110  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   348, -80  ,  91, -57  ,  344, -83  ,  346, -83  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   829, -127  ,  825, -130  ,  827, -130  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -672, -44  ,  -862, -34  ,  -846, -42  ,  -677, -47  ,  -673, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -479, -105  ,  -442, -103  ,  -430, -94  ,  -484, -102  ,  -483, -104  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -442, -103  ,  -479, -105  ,  -447, -106  ,  -443, -105  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   779, -162  ,  630, -162  ,  774, -165  ,  778, -164  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   713, -194  ,  721, -190  ,  706, -192  ,  709, -194  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1000, -35  ,  -862, -34  ,  1000, 500  ,  -1000, 500  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   96, -61  ,  91, -57  ,  94, -61  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   135, -93  ,  130, -89  ,  133, -93  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   344, -83  ,  339, -87  ,  341, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   918, -47  ,  1000, 500  ,  913, -51  ,  915, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   339, -87  ,  332, -92  ,  337, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   425, -41  ,  63, -41  ,  67, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   425, -41  ,  70, -44  ,  74, -47  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   839, -119  ,  630, -162  ,  829, -127  ,  835, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -404, -73  ,  -410, -78  ,  -408, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   102, -66  ,  96, -61  ,  100, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   108, -71  ,  102, -66  ,  106, -71  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   562, -117  ,  556, -112  ,  560, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -665, -40  ,  -862, -34  ,  -672, -44  ,  -666, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -495, -94  ,  -504, -87  ,  -501, -91  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -417, -84  ,  -504, -87  ,  -426, -91  ,  -420, -88  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   357, -73  ,  91, -57  ,  348, -80  ,  354, -77  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   63, -41  ,  425, -41  ,  52, -37  ,  57, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -430, -94  ,  -442, -103  ,  -434, -99  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -451, -110  ,  -447, -106  ,  -479, -105  ,  -473, -110  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -410, -78  ,  -417, -84  ,  -415, -84  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -374, -45  ,  -381, -51  ,  -379, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -363, -38  ,  -552, -41  ,  -506, -87  ,  -504, -87  ,  -374, -45  ,  -367, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -484, -102  ,  -430, -94  ,  -495, -94  ,  -488, -101  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -86, -100  ,  -155, -114  ,  -153, -116  ,  -115, -115  ,  -94, -108  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   556, -112  ,  546, -104  ,  549, -108  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -552, -41  ,  -363, -38  ,  -339, -32  ,  -562, -35  ,  -556, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -38  ,  -254, -33  ,  -35, -43  ,  -28, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   787, -157  ,  630, -162  ,  779, -162  ,  786, -159  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   620, -155  ,  611, -150  ,  612, -152  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   629, -160  ,  620, -155  ,  621, -157  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   927, -42  ,  1000, 500  ,  918, -47  ,  926, -44  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   228, -138  ,  242, -136  ,  258, -132  ,  275, -126  ,  193, -131  ,  194, -133  ,  210, -138  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   534, -94  ,  526, -87  ,  532, -94  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   611, -150  ,  600, -143  ,  607, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -719, -76  ,  -718, -74  ,  -807, -73  ,  -791, -81  ,  -749, -84  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   721, -190  ,  736, -186  ,  757, -176  ,  675, -182  ,  681, -186  ,  706, -192  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   774, -165  ,  630, -162  ,  758, -174  ,  770, -169  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -77, -88  ,  -254, -33  ,  -86, -98  ,  -77, -90  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -68, -78  ,  -254, -33  ,  -77, -88  ,  -68, -80  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -59, -68  ,  -68, -78  ,  -59, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   526, -87  ,  516, -78  ,  524, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   825, -130  ,  630, -162  ,  803, -146  ,  814, -140  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   87, -54  ,  425, -41  ,  77, -47  ,  85, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -677, -47  ,  -808, -71  ,  -807, -73  ,  -696, -60  ,  -685, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -57  ,  -59, -68  ,  -50, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   193, -131  ,  180, -124  ,  181, -126  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -155, -114  ,  -86, -100  ,  -238, -42  ,  -176, -107  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -808, -71  ,  -677, -47  ,  -846, -42  ,  -820, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   546, -104  ,  534, -94  ,  544, -104  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   369, -64  ,  91, -57  ,  357, -73  ,  359, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  953, -34  ,  1000, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -702, -64  ,  -807, -73  ,  -718, -74  ,  -714, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   332, -92  ,  316, -103  ,  330, -95  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   803, -146  ,  630, -162  ,  787, -157  ,  801, -149  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -35, -43  ,  -254, -33  ,  -50, -57  ,  -46, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   180, -124  ,  158, -110  ,  174, -122  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   154, -107  ,  275, -126  ,  135, -93  ,  149, -105  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   577, -128  ,  562, -117  ,  575, -128  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   600, -143  ,  580, -130  ,  596, -142  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   126, -86  ,  108, -71  ,  124, -86  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   757, -176  ,  758, -174  ,  630, -162  ,  658, -176  ,  675, -182  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -115, -115  ,  -153, -116  ,  -117, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   861, -100  ,  839, -119  ,  841, -119  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -381, -51  ,  -404, -73  ,  -402, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -410, -78  ,  -504, -87  ,  -417, -84  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -404, -73  ,  -381, -51  ,  -504, -87  ,  -410, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   516, -78  ,  490, -54  ,  514, -78  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   312, -107  ,  313, -105  ,  102, -66  ,  126, -86  ,  130, -89  ,  277, -124  ,  280, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  937, -37  ,  953, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -374, -45  ,  -504, -87  ,  -381, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   629, -160  ,  1000, 500  ,  490, -54  ,  577, -128  ,  611, -150  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   193, -131  ,  275, -126  ,  154, -107  ,  158, -110  ,  180, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   344, -83  ,  91, -57  ,  316, -103  ,  339, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -57  ,  -254, -33  ,  -68, -78  ,  -59, -68  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   913, -51  ,  861, -100  ,  863, -100  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   275, -126  ,  277, -124  ,  130, -89  ,  135, -93  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   577, -128  ,  490, -54  ,  526, -87  ,  562, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  927, -42  ,  937, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -659, -37  ,  -862, -34  ,  -665, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -659, -37  ,  -635, -32  ,  1000, 500  ,  -862, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -86, -100  ,  -86, -98  ,  -254, -33  ,  -238, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   313, -105  ,  96, -61  ,  102, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   913, -51  ,  1000, 500  ,  629, -160  ,  630, -162  ,  839, -119  ,  861, -100  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   829, -127  ,  630, -162  ,  825, -130  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   398, -48  ,  91, -57  ,  369, -64  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, -31  ,  1000, 500  ,  -264, -32  ,  -254, -33  ,  -27, -38  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   546, -104  ,  556, -112  ,  526, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   452, -41  ,  1000, 500  ,  27, -31  ,  52, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -339, -32  ,  -569, -34  ,  -562, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -339, -32  ,  1000, 500  ,  -586, -32  ,  -569, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  471, -45  ,  490, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  452, -41  ,  471, -45  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  0, -31  ,  27, -31  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -339, -32  ,  -264, -32  }
                    }
                     ,
                    {
                    pe_fixture_id = "t12", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -635, -32  ,  -586, -32  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

