-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["t3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -34, -117  ,  17, -126  ,  56, -95  ,  -36, -112  ,  -36, -116  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   931, -43  ,  1000, 500  ,  924, -45  ,  928, -45  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1000, -41  ,  -962, -41  ,  1000, 500  ,  -1000, 500  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   42, -117  ,  56, -95  ,  17, -126  ,  36, -124  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   668, -79  ,  673, -63  ,  673, -57  ,  578, -89  ,  578, -93  ,  631, -103  ,  650, -101  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   598, -109  ,  612, -111  ,  621, -109  ,  631, -103  ,  578, -93  ,  586, -103  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -55, -89  ,  -48, -96  ,  -57, -79  ,  -57, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -126  ,  -19, -131  ,  -2, -134  ,  7, -132  ,  17, -126  ,  -34, -117  ,  -32, -122  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   470, -87  ,  1000, 500  ,  -80, -76  ,  -57, -79  ,  465, -89  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   504, -81  ,  1000, 500  ,  493, -83  ,  499, -83  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49, -112  ,  56, -95  ,  42, -117  ,  44, -117  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   663, -89  ,  668, -79  ,  655, -95  ,  657, -95  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, -106  ,  -48, -96  ,  -48, -98  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   575, -83  ,  673, -57  ,  566, -73  ,  566, -75  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   924, -45  ,  1000, 500  ,  673, -57  ,  712, -57  ,  907, -50  ,  918, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -39, -106  ,  56, -95  ,  -57, -79  ,  -48, -96  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  949, -41  ,  1000, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   907, -50  ,  712, -57  ,  800, -63  ,  844, -63  ,  880, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -371, -71  ,  -306, -68  ,  1000, 500  ,  -962, -41  ,  -937, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   493, -83  ,  1000, 500  ,  470, -87  ,  488, -85  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56, -95  ,  -39, -106  ,  -36, -112  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   673, -57  ,  575, -83  ,  578, -89  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  931, -43  ,  949, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   424, -96  ,  459, -89  ,  -57, -79  ,  106, -101  ,  251, -111  ,  297, -111  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   673, -57  ,  1000, 500  ,  563, -70  ,  566, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -371, -71  ,  -796, -60  ,  -745, -66  ,  -526, -84  ,  -510, -84  ,  -444, -80  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -617, -85  ,  -551, -85  ,  -526, -84  ,  -745, -66  ,  -734, -69  ,  -656, -82  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   558, -70  ,  1000, 500  ,  504, -81  ,  510, -81  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  558, -70  ,  563, -70  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -127, -72  ,  -80, -76  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -206, -68  ,  -127, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "t3", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -306, -68  ,  -206, -68  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

