-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["t40"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -634, -259  ,  -637, -257  ,  -636, -259  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   565, -135  ,  461, -165  ,  570, -164  ,  574, -155  ,  574, -137  ,  570, -134  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -480, -341  ,  -485, -339  ,  -483, -341  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -475, -343  ,  -480, -341  ,  -478, -343  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -458, -350  ,  -463, -348  ,  -461, -350  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -191, -390  ,  -196, -388  ,  -194, -390  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -186, -392  ,  -191, -390  ,  -189, -392  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   574, -129  ,  569, -122  ,  564, -133  ,  574, -133  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -886, -39  ,  -890, -36  ,  -888, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -882, -42  ,  -886, -39  ,  -884, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -878, -45  ,  -882, -42  ,  -880, -45  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -874, -48  ,  -878, -45  ,  -876, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -870, -51  ,  -874, -48  ,  -872, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -637, -257  ,  -641, -254  ,  -639, -257  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   264, -378  ,  261, -372  ,  252, -358  ,  259, -393  ,  264, -387  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   369, -286  ,  366, -280  ,  357, -266  ,  260, -343  ,  364, -301  ,  369, -295  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   473, -187  ,  470, -181  ,  461, -167  ,  427, -216  ,  468, -202  ,  473, -196  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   574, -104  ,  571, -98  ,  569, -119  ,  574, -113  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   453, -222  ,  464, -221  ,  463, -219  ,  457, -218  ,  453, -220  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   666, -58  ,  680, -87  ,  683, -85  ,  686, -77  ,  677, -57  ,  676, -55  ,  670, -54  ,  666, -56  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   566, -87  ,  461, -165  ,  564, -133  ,  569, -119  ,  571, -98  ,  570, -91  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   252, -358  ,  261, -372  ,  260, -365  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   357, -266  ,  366, -280  ,  365, -273  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   461, -167  ,  470, -181  ,  469, -174  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   442, -217  ,  438, -219  ,  435, -223  ,  451, -222  ,  450, -219  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   655, -53  ,  651, -55  ,  648, -59  ,  664, -58  ,  663, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1000, -36  ,  -960, -36  ,  -936, -33  ,  1000, 500  ,  -1000, 500  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -857, -61  ,  -862, -57  ,  -859, -61  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -712, -201  ,  -717, -197  ,  -714, -201  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -683, -224  ,  -688, -220  ,  -685, -224  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   432, -218  ,  427, -216  ,  365, -251  ,  435, -223  ,  435, -221  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   645, -54  ,  640, -52  ,  566, -87  ,  648, -59  ,  648, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -657, -243  ,  -279, -362  ,  -664, -238  ,  -662, -241  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -451, -353  ,  -458, -350  ,  -454, -353  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   260, -343  ,  -186, -392  ,  -161, -402  ,  254, -348  ,  257, -347  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   365, -251  ,  -186, -392  ,  359, -256  ,  362, -255  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   464, -221  ,  453, -222  ,  365, -251  ,  469, -250  ,  473, -241  ,  473, -223  ,  471, -221  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   677, -57  ,  686, -77  ,  686, -59  ,  684, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -717, -197  ,  -723, -192  ,  -719, -197  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   468, -205  ,  427, -216  ,  473, -216  ,  473, -212  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   664, -41  ,  640, -52  ,  669, -52  ,  669, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  666, -35  ,  1000, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   264, -425  ,  264, -403  ,  259, -396  ,  -149, -407  ,  -53, -432  ,  -18, -435  ,  258, -435  ,  261, -433  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -196, -388  ,  -870, -51  ,  -868, -54  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -149, -407  ,  252, -358  ,  254, -348  ,  -161, -402  ,  -157, -405  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   666, -35  ,  640, -52  ,  664, -41  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   369, -311  ,  366, -308  ,  260, -343  ,  365, -342  ,  369, -333  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -463, -348  ,  -475, -343  ,  -466, -348  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   666, -58  ,  664, -58  ,  648, -59  ,  566, -87  ,  680, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -319, -360  ,  -451, -353  ,  -447, -356  ,  -435, -360  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -596, -283  ,  -614, -272  ,  -610, -276  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   569, -119  ,  564, -133  ,  569, -122  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -737, -180  ,  -750, -168  ,  -739, -180  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -641, -254  ,  -279, -362  ,  -657, -243  ,  -655, -246  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -723, -192  ,  -737, -180  ,  -725, -192  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -664, -238  ,  -683, -224  ,  -669, -236  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -842, -75  ,  -857, -61  ,  -844, -75  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -614, -272  ,  -634, -259  ,  -618, -271  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   468, -202  ,  427, -216  ,  468, -205  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -577, -294  ,  -596, -283  ,  -595, -285  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -773, -148  ,  -771, -148  ,  -789, -130  ,  -789, -132  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -125, -417  ,  -89, -426  ,  -53, -432  ,  -149, -407  ,  -145, -410  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -688, -220  ,  -712, -201  ,  -694, -217  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -750, -168  ,  -771, -148  ,  -752, -168  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -485, -339  ,  -634, -259  ,  -596, -283  ,  -577, -294  ,  -488, -339  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -161, -402  ,  -186, -392  ,  -184, -394  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -723, -192  ,  -664, -238  ,  -816, -102  ,  -816, -104  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   364, -301  ,  260, -343  ,  366, -308  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   359, -256  ,  -186, -392  ,  260, -343  ,  357, -266  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -634, -259  ,  -485, -339  ,  -279, -362  ,  -641, -254  ,  -637, -257  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   564, -133  ,  461, -165  ,  565, -135  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  566, -87  ,  640, -52  ,  666, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -319, -360  ,  -458, -350  ,  -451, -353  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   461, -165  ,  365, -251  ,  427, -216  ,  461, -167  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -510, -328  ,  -577, -294  ,  -576, -296  ,  -513, -328  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -723, -192  ,  -789, -130  ,  -737, -180  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   252, -358  ,  -149, -407  ,  259, -396  ,  259, -393  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -596, -283  ,  -634, -259  ,  -614, -272  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -279, -362  ,  -475, -343  ,  -458, -350  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -664, -238  ,  -688, -220  ,  -683, -224  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -664, -238  ,  -279, -362  ,  -842, -75  ,  -816, -102  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -279, -362  ,  -485, -339  ,  -475, -343  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   435, -223  ,  365, -251  ,  453, -222  ,  451, -222  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  461, -165  ,  566, -87  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1000, 500  ,  -890, -36  ,  -196, -388  ,  -186, -392  ,  365, -251  ,  461, -165  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -279, -362  ,  -266, -364  ,  -857, -61  ,  -842, -75  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -196, -388  ,  -862, -57  ,  -857, -61  ,  -266, -364  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -908, -33  ,  1000, 500  ,  -936, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -890, -36  ,  1000, 500  ,  -908, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "t40", density = 2, friction = 12, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -196, -388  ,  -890, -36  ,  -870, -51  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

